### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by fingermark** [appsforartists/ambidex-example--bike-index#8] opened 2015-02-02 00:52 UTC
`npm` fails notifying me that `Ambidex` is not in the npm registry.  Changing `package.json` to `ambidex` and re-running `npm install` seems to install everything just fine.

```
npm ERR! 404 Not Found: Ambidex
npm ERR! 404
npm ERR! 404 'Ambidex' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ambidex-example--bike-index'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

After changing package.json with `ambidex` I get:

```
Module not found: Error: Cannot resolve module 'react-hot-loader'
```

I add that, then I get 

   Cannot resolve module 'jsx-loader'

Then I give up.

**Comment by appsforartists** [comment] 2015-02-02 01:06
Sounds like a dupe of #7.

I had to lowercase Ambidex at the last minute to get it into npm, and that's causing some weirdness.  Hoping to get to the bottom of it next week.

**Closed as completed by appsforartists** 2015-02-02 01:06 UTC
